module.exports = {
    channels: {
      TO_SERVER_OPEN_DIRECTORY_DIALOG_FOR_PLAYGROUND: 'TO_SERVER_OPEN_DIRECTORY_DIALOG_FOR_PLAYGROUND',
      TO_SERVER_OPEN_DIRECTORY_DIALOG_FOR_SIMULATOR: 'TO_SERVER_OPEN_DIRECTORY_DIALOG_FOR_SIMULATOR',
      TO_SERVER_OPEN_DIRECTORY_DIALOG: 'TO_SERVER_OPEN_DIRECTORY_DIALOG',
      TO_SERVER_OPEN_CREATE_PROJECT_DIALOG: 'TO_SERVER_OPEN_CREATE_PROJECT_DIALOG',
      GIVE_CLOSE_PROJECT: "GIVE_CLOSE_PROJECT",
      GIVE_TEMPLATIVE_ROOT_FOLDER: "GIVE_TEMPLATIVE_ROOT_FOLDER",
      GIVE_PLAYGROUND_FOLDER: "GIVE_PLAYGROUND_FOLDER",
      GIVE_SIMULATOR_FOLDER: "GIVE_SIMULATOR_FOLDER",
      TO_SERVER_OPEN_URL: "TO_SERVER_OPEN_URL",

      GIVE_LOGOUT: "GIVE_LOGOUT",
      GIVE_LOGGED_IN: "GIVE_LOGGED_IN",
      GIVE_NOT_LOGGED_IN: "GIVE_NOT_LOGGED_IN",
      GIVE_UNABLE_TO_LOG_IN: "GIVE_UNABLE_TO_LOG_IN",
      GIVE_INVALID_LOGIN_CREDENTIALS: "GIVE_INVALID_LOGIN_CREDENTIALS",
      TO_SERVER_IS_LOGGED_IN: "TO_SERVER_IS_LOGGED_IN",
      TO_SERVER_LOGIN: "TO_SERVER_LOGIN",
    },
  };