module.exports = {
    channels: {
      TO_SERVER_OPEN_DIRECTORY_DIALOG_FOR_PLAYGROUND: 'TO_SERVER_OPEN_DIRECTORY_DIALOG_FOR_PLAYGROUND',
      TO_SERVER_OPEN_DIRECTORY_DIALOG: 'TO_SERVER_OPEN_DIRECTORY_DIALOG',
      TO_SERVER_OPEN_CREATE_PROJECT_DIALOG: 'TO_SERVER_OPEN_CREATE_PROJECT_DIALOG',
      GIVE_CLOSE_PROJECT: "GIVE_CLOSE_PROJECT",
      GIVE_TEMPLATIVE_ROOT_FOLDER: "GIVE_TEMPLATIVE_ROOT_FOLDER",
      GIVE_PLAYGROUND_FOLDER: "GIVE_PLAYGROUND_FOLDER",
      TO_SERVER_OPEN_URL: "TO_SERVER_OPEN_URL"
    },
  };