on:
  push: null

permissions:
  contents: write

jobs:
  templative:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          # - macos-latest
          # - macos-13-xlarge
        node:
          - 18
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pipenv
        run: pip install pipenv pyinstaller

      - name: Install Requirements
        run: |
          cd python
          pipenv install
          pipenv requirements > req.txt
          pip install -r req.txt
          cd ..

      - name: Create Templative App/Exe
        run: pyinstaller --distpath ./dist -y -n templative --onefile
          ./python/templative/__main__.py --hidden-import
          engineio.async_drivers.aiohttp --hidden-import engineio.async_aiohttp
          --collect-all templative

      - name: Zip Templative Server Windows
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path dist/* -Destination templative_${{matrix.os}}.zip

      - name: Zip Templative Server OSX
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-latest-xlarge'
        run: zip templative_${{matrix.os}}.zip dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: templative-server-${{matrix.os}}
          path: ./templative_${{matrix.os}}.zip

  react:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          # - macos-latest
          # - macos-13-xlarge
        node:
          - 18
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        run: npm install

      - name: Build React Files
        run: npm run react-build

      - name: Zip React Server Windows
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path build/* -Destination react_${{matrix.os}}.zip

      - name: Zip React Server OSX
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-latest-xlarge'
        run: zip react_${{matrix.os}}.zip build/

      - name: Upload Artifact Windows
        uses: actions/upload-artifact@master
        with:
          name: react-server-${{matrix.os}}
          path: ./react_${{matrix.os}}.zip

  electron:
    needs: [react, templative]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          # - macos-latest
          # - macos-13-xlarge
        node:
          - 18
    steps:
      - uses: actions/checkout@v2

      - name: Download Templative Server
        uses: actions/download-artifact@master
        with:
          name: templative-server-${{matrix.os}}
          path: ./

      - name: Unzip Templative Windows
        if: matrix.os == 'windows-latest'
        run: Expand-Archive -LiteralPath "templative_${{matrix.os}}.zip" -DestinationPath "./python"
    
      - name: Unzip Templative OSX
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-latest-xlarge'
        run: unzip -j "./templative_${{matrix.os}}.zip" -d "./python" 

      - name: Download React Server 
        uses: actions/download-artifact@master
        with:
          name: react-server-${{matrix.os}}
          path: ./

      - name: Unzip React Windows
        if: matrix.os == 'windows-latest'
        run: Expand-Archive -LiteralPath "react_${{matrix.os}}.zip" -DestinationPath "./build"
    
      - name: Unzip React OSX
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-latest-xlarge'
        run: unzip "./react_${{matrix.os}}.zip" -d "./build"
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        run: npm install

      - name: Create Electron Application
        run: npm run make

      - name: Zip Output Windows
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path out/* -Destination ./templative_windows.zip

      - name: Zip Output MacOS
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-latest-xlarge'
        run: zip ./templative_${{matrix.os}}.zip out/ 

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: templative-app-${{matrix.os}}
          path: ./templative_${{matrix.os}}.zip


  release:
    permissions:
      contents: write
    needs: [electron]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        node:
          - 18
    steps:
      - name: Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.run_number }}
          tag_name: ${{ github.run_number }}

  artifacts:
    needs: [release]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          # - macos-latest
          # - macos-13-xlarge
        node:
          - 18
    steps:   
      
      - name: Download Templative App
        uses: actions/download-artifact@master
        with:
          name: templative-app-${{matrix.os}}
          path: ./

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.release.outputs.upload_url}}
          asset_path: ./templative_windows-latest.zip
          asset_name: templative_windows-latest.zip
          asset_content_type: application/zip
