on:
  push: null

permissions:
  contents: write

jobs:
  templative:
    if: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          # - macos-13-xlarge
        node:
          - 18
        python:
          - 3.11
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pipenv
        run: pip install pipenv pyinstaller

      - name: Install Requirements
        run: |
          cd python
          pipenv install
          pipenv requirements > req.txt
          pip install -r req.txt
          cd ..

      - name: Create Templative App/Exe
        run: pyinstaller --distpath ./bin -y -n templative --onefile
          ./python/templative/__main__.py --hidden-import
          engineio.async_drivers.aiohttp --hidden-import engineio.async_aiohttp
          --collect-all templative

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        run: npm install

      - name: Build React Files
        run: npm run react-build

      - name: Create Electron Application and Upload it S3
        run: npm run publish