on:
  push: null

permissions:
  contents: write

jobs:
  templative:
    if: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          # - macos-13-xlarge
        node:
          - 18
        python:
          - 3.11
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pipenv
        run: pip install pipenv pyinstaller

      - name: Install Requirements
        run: |
          cd python
          pipenv install
          pipenv requirements > req.txt
          pip install -r req.txt
          cd ..

      - name: Create Templative App/Exe
        run: pyinstaller --distpath ./python -y -n templative --onefile
          ./python/templative/__main__.py --hidden-import
          engineio.async_drivers.aiohttp --hidden-import engineio.async_aiohttp
          --collect-all templative

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Packages
        run: npm install

      - name: Build React Files
        run: npm run react-build

      - name: Create Electron Application
        run: npm run make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: templative-app-${{matrix.os}}
          path: ./out

  release:
    if: true
    permissions:
      contents: write
    needs: [templative]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        node:
          - 18
    steps:
      - name: Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.run_number }}
          tag_name: ${{ github.run_number }}

  artifacts:
    if: true
    needs: [release]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          # - macos-13-xlarge Enable a runner
        node:
          - 18
    steps:   
      - uses: actions/checkout@v2

      - name: Download Templative App
        uses: actions/download-artifact@master
        with:
          name: templative-app-${{matrix.os}}
          path: ./

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.release.outputs.upload_url}}
          asset_path: ./out
          asset_name: templative_${{matrix.os}}.zip
          asset_content_type: application/zip
