on:
  push: null

permissions:
  contents: write

jobs:
  templative:
    if: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        node:
          - 18
        python:
          - 3.11
    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        shell: bash
        run: |
          PACKAGE_VERSION=$(npm pkg get version --workspaces=false | tr -d \")
          echo $PACKAGE_VERSION
          echo "current-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Move Windows Squirrel Files into directory 
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          ls
          mkdir ./Templative-win32-x64-${{steps.package-version.outputs.current-version}}
          tocuh ./Templative-win32-x64-${{steps.package-version.outputs.current-version}}/hello.txt
          ls
          cd ..

      - name: Zip Windows Squirrel Files
        shell: bash
        if: matrix.os == 'windows-latest' 
        run: |
          zip -r ./Templative-win32-x64-${{steps.package-version.outputs.current-version}}.zip ./Templative-win32-x64-${{steps.package-version.outputs.current-version}}/*
          ls

      - name: Deploy Windows to S3
        if: matrix.os == 'windows-latest'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./Templative-win32-x64-${{steps.package-version.outputs.current-version}}.zip s3://templative-artifacts/win32/x64 --region us-west-2